select 
	CONVERT(varchar,FIMEXECUCAO,103) ENCERRAMENTO,
	UF,
	MUNICIPIO,
	COUNT(*) QTE,
	ATIVIDADE
from 
	CLICK_FECHADAS 
where 
	FIMEXECUCAO >= '2021-01-01' 
	and ATIVIDADE 
	    in ('REMANEJAMENTO - BL',
		'REMANEJAMENTO - BL E IPTV',
		'REMANEJAMENTO - IPTV',
		'REMANEJAMENTO - BL E VOIP',
		'REMANEJAMENTO - VOIP E IPTV',
		'REMANEJAMENTO - VOIP',
		'REMANEJAMENTO - BL E VOIP E IPTV')
	and ESTADO = 'concluído com sucesso'
GROUP BY 
	CONVERT(varchar,FIMEXECUCAO,103),
	UF,
	MUNICIPIO,
	ATIVIDADE

